version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ../cache/activity/postgres-data:/var/lib/postgresql/data
      - ../docker/postgres/web3-indexer-sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    
  redis:
    image: redis:bullseye
    user: redis:redis
    ports: 
      - 6379:6379
    volumes:
      - ../cache/activity/redis-data:/data

  godwoken:
    image: nervos/godwoken-prebuilds:v0.7.0-rc1
    restart: always
    volumes:
    - ../testnet-godwoken-readonly-config.toml:/deploy/config.toml
    - ../block-producer-private-key.txt:/deploy/pk
    - ../cache/activity/store.db:/store.db
    environment:
      RUST_BACKTRACE: 1
    command: godwoken run -c /deploy/config.toml
    ports:
      - 8119:8119
    depends_on:
      - postgres

  web3:
    image: nervos/godwoken-web3-prebuilds:v0.8.1-rc2
    volumes: 
      - ../web3.env:/godwoken-web3/packages/api-server/.env
    working_dir: /godwoken-web3
    command: yarn workspace @godwoken-web3/api-server start
    ports:
      - 8024:8024
    depends_on: 
      - redis
      - postgres
      - godwoken